- name: Установка Kubernetes на Master и Worker
  hosts: all
  become: yes
  tasks:

    - name: Обновление YUM и установка epel-release
      yum:
        name:
          - epel-release
        state: present
        update_cache: yes

    - name: Удаление всех старых репозиториев Kubernetes
      shell: rm -f /etc/yum.repos.d/kubernetes.repo
      args:
        removes: /etc/yum.repos.d/kubernetes.repo
      ignore_errors: yes

    - name: Установить зависимости
      yum:
        name:
          - curl
          - vim
          - git
          - wget
          - net-tools
          - socat
          - conntrack
          - ipvsadm
          - iproute-tc
          - bash-completion
          - htop
        state: present

    - name: Отключение SELinux
      selinux:
        state: disabled

    - name: Отключение swap
      command: swapoff -a
      ignore_errors: yes  # Чтобы не прерывало выполнение, если swap уже отключен

    - name: Удалить swap из /etc/fstab
      lineinfile:
        path: /etc/fstab
        regexp: '.*swap.*'
        state: absent

    - name: Проверка, установлен ли firewalld
      command: systemctl is-active firewalld
      register: firewalld_status
      ignore_errors: yes

    - name: Отключение firewalld, если он работает
      systemd:
        name: firewalld
        state: stopped
        enabled: no
      when: firewalld_status.stdout == "active"

    - name: Проверка, установлен ли iptables
      command: systemctl is-active iptables
      register: iptables_status
      ignore_errors: yes

    - name: Отключение iptables, если он работает
      systemd:
        name: iptables
        state: stopped
        enabled: no
      when: iptables_status.stdout == "active"
