apiVersion: v1
kind: Namespace
metadata:
  name: directus
---
apiVersion: v1
kind: Service
metadata:
  name: directus
  namespace: directus
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8055
  selector:
    app: directus
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: directus
  namespace: directus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: directus
  template:
    metadata:
      labels:
        app: directus
    spec:
      containers:
        - name: directus
          image: directus/directus:latest
          ports:
            - containerPort: 8055
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: directus-ingress
  namespace: directus
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: directus.k8s.local.home
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: directus
                port:
                  number: 80
