all:
  hosts:
    master:
      ansible_host: 192.168.8.3
      ip: 192.168.8.3
      access_ip: 192.168.8.3
    worker:
      ansible_host: 192.168.8.4
      ip: 192.168.8.4
      access_ip: 192.168.8.4

  children:
    kube_control_plane:
      hosts:
        master:
    kube_node:
      hosts:
        worker:
    etcd:
      hosts:
        master:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}